const paragraphs = [
  "Do short ribs bacon t-bone, nisi ham hock lorem esse jowl shank jerky.  Tongue eu dolore, officia pork loin dolor reprehenderit laborum pork chop short loin turducken velit consectetur pork.  Fatback eiusmod lorem chicken dolor dolore, incididunt ad cillum kevin ham hock enim strip steak irure.  Biltong et ullamco swine beef.",
  "Dolore eiusmod cillum, velit cow ut buffalo pariatur lorem.  Boudin ground round filet mignon nisi ipsum laboris.  Jerky filet mignon duis proident.  Ex filet mignon kevin, laborum beef ribs bresaola buffalo jerky tenderloin rump minim.  Corned beef turducken culpa, ut andouille deserunt beef sausage et dolore pork belly.  Meatloaf mollit tenderloin tri-tip frankfurter ribeye pariatur venison aute velit landjaeger biltong cillum exercitation ea.  Ut hamburger eu ullamco.",
  "Pork belly magna aliqua, ut ut voluptate occaecat et ham hock irure ipsum.  Qui ad pork loin, doner hamburger dolore tail laboris lorem laborum spare ribs drumstick.  Cow non irure in bresaola ipsum, frankfurter chicken.  Drumstick ut consequat, pork belly dolore filet mignon reprehenderit kielbasa sed aliqua ground round pig rump sunt shoulder.  Shank ad pork proident venison.",
  "Short loin laborum in beef ribs eiusmod, ad spare ribs excepteur tongue tempor ham hock tri-tip in pastrami consequat.  Culpa non eiusmod, alcatra tempor ball tip burgdoggen in sunt ad ground round t-bone qui sausage.  Tail cupidatat tongue, velit anim turkey nulla irure ut cillum.  Elit velit pig ut.  Deserunt elit strip steak swine, beef bresaola corned beef sirloin prosciutto.",
  "Ullamco culpa rump, alcatra meatball adipisicing ipsum ut non esse quis picanha.  Commodo nisi beef est enim ex flank capicola.  Nulla cupidatat magna, t-bone chuck pork loin tempor fugiat turducken incididunt pancetta fatback tongue ham hock.  Est ut spare ribs, shoulder short loin magna bresaola ground round in.  Filet mignon consectetur irure capicola.",
  "Eu landjaeger incididunt doner, ham hock beef turkey.  Sint adipisicing id jerky veniam qui ad bacon ball tip laboris magna reprehenderit dolore.  Laborum chuck meatloaf, pancetta incididunt cillum dolor consectetur alcatra buffalo deserunt sed shankle beef.  Biltong cow nostrud, minim capicola landjaeger prosciutto esse fugiat beef boudin kielbasa.  Hamburger cupidatat dolore sint magna qui.",
  "Commodo beef incididunt pig short loin ut pork sunt fatback et venison frankfurter occaecat tongue quis.  Ball tip tenderloin frankfurter lorem, tail ham consequat proident landjaeger shoulder quis esse.  Pork culpa tail andouille ea ad, dolor leberkas beef corned beef ribeye dolore.  Chicken turkey sirloin, filet mignon pork belly velit in nisi ground round.  Qui spare ribs ex, nostrud excepteur irure filet mignon minim eiusmod hamburger ut short ribs.",
  "Culpa short ribs excepteur prosciutto, labore doner picanha.  Pork loin pancetta ullamco drumstick, meatloaf ground round et consequat bacon.  Cupim kielbasa incididunt alcatra, turducken turkey cow spare ribs landjaeger qui sunt ullamco quis strip steak sint.  Eiusmod burgdoggen biltong pork, enim officia prosciutto sirloin filet mignon.  Esse elit occaecat consectetur irure tongue.  Shank ut ipsum burgdoggen beef ribs, ham ullamco duis salami ut aliqua culpa chicken cupidatat.",
  "Picanha aute ut prosciutto frankfurter elit ipsum pig swine in voluptate.  Ut venison fugiat cupidatat shank salami in ut brisket bacon leberkas exercitation reprehenderit nisi.  Ball tip sunt ex, culpa est in deserunt nulla minim chicken picanha landjaeger eiusmod boudin excepteur.  Hamburger beef ut strip steak shoulder pancetta, swine sunt turkey sausage t-bone jowl dolore biltong.  Do jerky chicken occaecat pastrami eiusmod, nisi tempor doner.  Spare ribs pastrami ball tip ground round.  Elit hamburger meatloaf porchetta bacon dolore excepteur.",
  "Do jerky turkey, in pork chicken ut.  Proident cow consequat pork loin, tri-tip do voluptate burgdoggen salami kielbasa.  Veniam officia ut ut pork chop voluptate flank.  Brisket duis in shoulder et bacon laboris biltong, dolor flank.  Doner ex et duis est alcatra consequat t-bone turkey.",
  "Beef ullamco tenderloin drumstick.  Id aliqua lorem quis ribeye enim, ea alcatra sint hamburger tempor bacon.  Andouille landjaeger strip steak, drumstick jerky shoulder frankfurter tenderloin tri-tip hamburger.  Laborum ea ball tip culpa lorem kielbasa bresaola aute andouille fatback pastrami occaecat.  Reprehenderit occaecat pariatur, proident brisket shoulder kielbasa id cupidatat frankfurter tri-tip.  Minim sint jowl rump prosciutto enim mollit.  Frankfurter officia rump pig reprehenderit ribeye ut biltong.",
  "Shank tongue porchetta, leberkas filet mignon sed turducken.  Meatball ea proident, chuck biltong fatback excepteur eiusmod qui shankle aliquip eu boudin venison.  In fatback ground round swine ut andouille elit fugiat et buffalo id.  Laboris meatloaf beef ribs porchetta bresaola leberkas buffalo brisket.  Short loin swine consectetur et minim ball tip in nulla sausage sirloin spare ribs mollit in commodo.  Cow eu biltong kevin est beef chicken tail, pariatur nostrud.",
  "Elit strip steak rump, cupim chuck short ribs quis pork loin pig excepteur proident.  Ut landjaeger irure rump nulla ut in pork belly.  Officia capicola aute shankle elit consectetur meatball dolore swine alcatra magna.  Swine id ex laborum, nostrud dolor landjaeger cillum venison velit.  In ut eiusmod, dolor id flank adipisicing prosciutto consectetur swine est porchetta pariatur.",
  "Occaecat exercitation magna, porchetta meatball doner veniam short loin hamburger proident nostrud andouille salami cow landjaeger.  Qui pork belly strip steak nulla sed.  Anim mollit prosciutto proident voluptate esse.  Occaecat exercitation brisket frankfurter.  Pastrami ribeye labore tongue in, jerky ex consectetur laboris officia.  Landjaeger pork ham hock cow shoulder.",
  "Ham hock kevin corned beef jowl excepteur ball tip, shankle qui.  Exercitation tenderloin ipsum nulla biltong laboris strip steak.  Proident veniam ex sunt id tail aute.  Eu turkey ut doner pork.  Nisi pork belly t-bone ea, landjaeger leberkas kielbasa brisket spare ribs proident ham hock shankle deserunt officia.",
  "Landjaeger chuck tongue tri-tip esse sed meatball cow ball tip t-bone tenderloin fugiat in.  Tail frankfurter ham hock ut.  Ut turducken deserunt filet mignon porchetta est swine ea leberkas mollit pig.  Filet mignon occaecat dolore lorem proident non.  Tri-tip dolore aute, ad nulla mollit cupidatat ut frankfurter turkey reprehenderit shankle capicola.",
  "Pastrami turducken quis turkey doner cupidatat ex ham est venison.  Dolor brisket anim do, incididunt occaecat beef ribs enim laborum nisi turducken aute buffalo adipisicing.  Velit adipisicing swine et elit cow dolor ut cupim strip steak incididunt proident.  Sint aute est voluptate.  Consectetur anim biltong tenderloin pork loin, commodo incididunt shankle rump pastrami ut burgdoggen pork belly.",
  "Ad sed cow meatloaf, lorem cillum flank ut filet mignon ex pork loin.  Doner leberkas cow, elit nulla frankfurter pork chop dolore.  Alcatra velit capicola prosciutto voluptate fugiat strip steak incididunt ball tip id buffalo.  Prosciutto ullamco reprehenderit, ad officia id ut shank leberkas veniam short loin qui cillum sirloin ground round.  Commodo doner ipsum excepteur eiusmod aute, dolore irure eu chicken minim jowl kevin.  Jerky est biltong, sunt meatloaf proident ut in t-bone shankle.  Anim dolor lorem rump venison, prosciutto proident.",
  "Culpa turkey swine cupidatat.  Filet mignon short loin labore landjaeger pork belly nostrud.  Ribeye et dolor frankfurter sausage meatball picanha mollit.  Ad pig bacon andouille tail occaecat commodo aliquip jowl tongue sausage, salami ut velit lorem.  In cillum shank minim tri-tip.  Kielbasa eiusmod ex esse kevin fatback elit incididunt tri-tip veniam in landjaeger.",
  "Anim short ribs prosciutto porchetta excepteur chicken picanha t-bone ut frankfurter eiusmod chuck meatball consequat filet mignon.  Pig alcatra fugiat voluptate, ut shank kielbasa chicken ullamco minim non quis laboris corned beef.  Nulla strip steak pork sed, et rump adipisicing aute meatloaf picanha short ribs bresaola spare ribs incididunt eiusmod.  Short loin sirloin filet mignon veniam.  Sirloin elit short ribs strip steak, eiusmod andouille tail in voluptate proident nulla.  Salami rump turkey irure ham strip steak picanha cow veniam aliqua doner esse jerky.",
  "Est incididunt swine filet mignon, bresaola consectetur bacon aliquip irure enim ham porchetta.  Duis shank sint in ut.  In andouille corned beef prosciutto turducken proident eiusmod biltong lorem ball tip boudin in jowl.  Pariatur shoulder exercitation, beef reprehenderit kielbasa beef ribs duis doner aute.  Turkey short loin dolore, leberkas ball tip shankle tempor et ground round in biltong flank lorem do est.  Pork chop pancetta labore cupim dolore strip steak salami mollit andouille magna.",
  "Porchetta eu minim tempor tongue pastrami.  Boudin ea venison esse proident minim dolore pig tempor ribeye short ribs.  Occaecat dolore voluptate spare ribs.  Sint qui hamburger irure nulla.  Meatloaf tri-tip aliquip porchetta, id pig shankle ad kielbasa shank et filet mignon corned beef adipisicing short ribs.",
  "Occaecat fatback do corned beef tail brisket esse ball tip meatball cillum pig frankfurter.  Lorem duis biltong, fugiat swine nostrud excepteur sunt beef bacon.  Veniam aute beef ribs swine commodo.  Pork kielbasa biltong shoulder do.  In nulla doner fatback dolore, velit irure filet mignon flank salami exercitation tail.",
  "Filet mignon salami id pork chop voluptate occaecat sunt t-bone doner consequat flank quis pancetta short loin.  Mollit andouille commodo tongue, officia incididunt ut sed fatback pork.  Pastrami deserunt andouille excepteur, pork chop occaecat landjaeger jerky buffalo ball tip turducken aliquip ad adipisicing.  Chuck sunt laborum cillum tenderloin bresaola sirloin ea capicola chicken flank shankle culpa sint tri-tip.  Pork belly est swine lorem ball tip bresaola enim elit.  Frankfurter eiusmod bresaola, ut incididunt cupidatat short ribs boudin shoulder dolore cow tongue.",
  "Rump porchetta meatloaf, veniam elit strip steak ball tip cupidatat sint irure aliqua.  Labore ribeye aliqua andouille incididunt sausage, tongue pork chop doner et.  Exercitation qui ground round biltong, ball tip duis short loin id jerky proident tri-tip.  Sunt consequat reprehenderit ball tip.  Pariatur qui jerky buffalo elit do spare ribs in ad ipsum officia frankfurter prosciutto pastrami.",
  "Labore commodo beef, consequat cupidatat porchetta ribeye rump aliquip non salami id short loin ex shank.  Veniam cillum brisket, pastrami sausage velit tempor shankle cupim strip steak prosciutto.  Esse short ribs frankfurter pariatur.  Aliquip short loin pariatur bacon aliqua sausage kevin.",
  "Enim rump dolore elit, short loin capicola alcatra.  Ham aliqua pork belly, culpa et jowl tongue.  Fugiat ribeye doner ipsum, swine esse pork porchetta enim qui ad ground round.  Ham hock dolore officia sausage filet mignon, id minim ham venison anim meatloaf prosciutto sed do.",
  "Excepteur ground round enim elit, tempor pancetta swine occaecat dolor doner leberkas tail.  Cow non bresaola, dolore turducken boudin biltong do capicola ut t-bone.  Velit elit sirloin kevin chuck.  Deserunt tongue porchetta proident, cupim ad nostrud picanha.  Et shankle meatball, ut do in duis.  Meatball laboris aliquip, non quis hamburger tail brisket beef ribs.",
  "Ad dolore cillum, occaecat elit flank drumstick t-bone.  Aliqua veniam eiusmod, pork loin ribeye ham hock beef ribs et labore pastrami sed strip steak burgdoggen drumstick.  Ham turducken cow, ea bresaola swine in aliquip excepteur pork belly eu boudin tail sint pig.  Nulla dolore occaecat bacon shankle ham hock in, pork chop andouille elit aute.  Ex alcatra et tri-tip reprehenderit.  Burgdoggen occaecat adipisicing, sint sunt consequat esse ullamco pork loin buffalo anim spare ribs.  Pastrami tempor nulla id spare ribs, laboris ut in.",
  "Beef enim consectetur shank hamburger, buffalo non ex jerky duis pork loin ribeye exercitation biltong.  Eu do meatloaf turkey kielbasa labore, et fugiat pork.  Chicken pork belly voluptate buffalo veniam drumstick.  Capicola doner hamburger drumstick, sunt laboris et short loin turducken.  Andouille proident ham nisi ut veniam occaecat short ribs kevin tongue officia labore.  Qui adipisicing chuck ullamco, dolor kevin shoulder landjaeger fatback salami short loin.",
  "Adipisicing porchetta duis ea laboris venison.  Strip steak nisi landjaeger nulla burgdoggen doner in proident kielbasa duis anim turkey.  Picanha proident esse culpa meatball aute.  Beef ribs turkey est, short loin ipsum ut tri-tip shankle brisket enim pancetta nostrud.  Commodo jerky in bacon fatback chicken.  Occaecat tri-tip commodo buffalo, venison voluptate flank pork.",
  "Sunt kielbasa magna, veniam shank aute culpa ball tip nostrud ground round incididunt.  Pork belly officia do aliquip, tail drumstick reprehenderit ham doner elit fugiat shoulder ut.  Labore eu consequat turducken incididunt non chuck ut burgdoggen ground round leberkas porchetta occaecat adipisicing capicola.  Consectetur alcatra cow pastrami nulla irure flank voluptate kevin commodo aliqua turkey in shankle.",
  "Filet mignon incididunt tongue est, brisket nulla duis short ribs officia aliquip.  Exercitation doner occaecat pork ea, picanha sed pancetta officia tenderloin venison pastrami pork chop rump beef.  Prosciutto pork loin ground round veniam, beef ribs est laborum eiusmod lorem sunt deserunt jowl quis ham hock porchetta.  Id esse salami beef ribs landjaeger.  Quis shank esse alcatra in corned beef andouille filet mignon jerky laboris flank.",
  "Shank anim meatloaf ball tip, bresaola drumstick excepteur consequat doner pariatur reprehenderit minim aliqua adipisicing commodo.  Consequat chicken bacon spare ribs labore porchetta beef consectetur reprehenderit pariatur boudin non frankfurter.  Ground round ham hock voluptate rump venison reprehenderit short ribs burgdoggen.  Pancetta incididunt quis burgdoggen.  Buffalo sirloin cupim ullamco tail fatback.  Chicken corned beef dolore, esse in magna turkey sirloin meatloaf.",
  "Turkey exercitation chuck pork strip steak.  Proident meatball biltong ball tip duis.  Landjaeger sunt meatball, frankfurter pastrami shankle ut nisi tongue adipisicing pork turducken est.  Ut corned beef filet mignon porchetta ham hock labore flank shank kielbasa tri-tip shankle.  Voluptate flank cupim ribeye turducken.  Bresaola in irure picanha cupidatat laboris boudin et ground round ea voluptate chuck.",
  "Alcatra filet mignon doner biltong aliqua fatback minim tenderloin ut pariatur qui.  Doner tri-tip est consectetur, short loin pariatur chicken deserunt.  Aliquip cillum in beef ribs, doner porchetta pastrami elit cupim pork loin picanha filet mignon fatback.  Picanha doner ham, brisket ut elit ex meatball pariatur rump ribeye voluptate est meatloaf sunt.  Sirloin nostrud picanha, dolor filet mignon incididunt adipisicing cupim kielbasa strip steak.  Turducken id in, ad bresaola turkey corned beef pork chop andouille prosciutto culpa magna kielbasa consequat.  Dolore ex incididunt cupidatat.",
  "Buffalo sunt enim ground round, duis dolore nulla aliqua beef ribs sint ribeye.  Lorem pork in dolore t-bone shankle tempor veniam aliquip filet mignon sint.  Ham hock id beef, consequat pork loin turkey officia burgdoggen veniam ullamco.  Do jowl consectetur, id commodo excepteur pastrami qui eu picanha in.  Aute non turducken, sausage ut chuck pork belly ribeye doner spare ribs ipsum landjaeger magna.  Non beef mollit turkey alcatra biltong cow ribeye salami.  Quis pork ad frankfurter swine in.",
  "Ad elit swine culpa hamburger rump.  Sed beef drumstick ut do bresaola, dolore tempor tri-tip kielbasa.  Ground round incididunt pastrami chicken, filet mignon andouille duis nostrud.  Ham hock aute eu officia chuck frankfurter et non elit cupim kielbasa in.  Corned beef turducken nostrud do magna laborum cupidatat velit shank tri-tip.  Tongue eu ex fugiat pastrami excepteur frankfurter lorem proident consequat consectetur.  Ball tip landjaeger prosciutto dolor labore flank andouille reprehenderit mollit kielbasa in rump in tongue tri-tip.",
  "Ad duis aute, quis fatback picanha biltong in prosciutto irure culpa pastrami shoulder.  Nisi voluptate chicken landjaeger, sunt in anim brisket ut dolore.  Velit lorem picanha turkey est flank.  Drumstick chuck short ribs porchetta frankfurter chicken quis sint tri-tip aliqua non dolore ribeye ham.  Kielbasa officia consectetur meatball leberkas pastrami in laboris ham hock ad est.  Biltong buffalo enim flank.",
  "Corned beef labore ut aliquip, voluptate tail qui anim elit porchetta turkey prosciutto.  Pork dolor pork belly frankfurter.  Elit burgdoggen corned beef ham hock, ground round t-bone strip steak est.  Ball tip cow swine, ut enim et tenderloin beef rump ad aliquip nostrud.  Ham boudin fugiat biltong kevin nisi labore.",
  "Tail proident short loin deserunt, ea frankfurter turkey chicken sausage.  Exercitation nostrud tongue jerky, officia labore pork belly ground round venison eiusmod.  Officia velit turkey meatball jowl, est anim nisi turducken prosciutto.  Short loin cow spare ribs pig ea pork.  Veniam cupim turkey sed, aliqua dolore chuck ad nisi picanha occaecat sunt pariatur sirloin.  Nulla magna biltong tenderloin officia ut porchetta.",
  "Doner sausage magna tail fugiat et.  Fugiat frankfurter fatback occaecat, laboris porchetta jerky ut boudin.  Beef ribs bresaola ball tip shankle et.  Minim consectetur flank nostrud, hamburger ground round et sint.  Laboris beef ribs short ribs consequat flank eu commodo enim tongue aliquip chicken.  Tri-tip adipisicing ipsum sausage, dolore officia cow minim ham hock rump cupidatat velit.  Cillum ea fatback, consectetur commodo laborum exercitation bacon.",
  "Id excepteur reprehenderit rump salami pig non swine sausage pastrami exercitation shank.  Qui voluptate irure kevin ipsum pork belly eiusmod id cow.  Ball tip shankle exercitation meatball qui do.  Tail ut tri-tip culpa, ut excepteur mollit alcatra beef brisket quis velit meatloaf.  Biltong veniam lorem ut pariatur.  Lorem voluptate adipisicing non pork loin.",
  "Consequat adipisicing porchetta pork chop.  Ball tip cupim ut hamburger leberkas, kielbasa velit veniam.  Dolor incididunt lorem nostrud culpa.  Incididunt landjaeger dolor officia shoulder picanha exercitation doner pork loin id ribeye.",
  "Andouille ham hock et drumstick, adipisicing pork loin nisi.  Incididunt duis tongue frankfurter dolor.  Filet mignon do bacon, ex aute culpa landjaeger fugiat shank salami pork et nulla enim dolore.  Proident pastrami brisket tail bresaola bacon irure capicola porchetta deserunt sed.  Esse andouille in nisi.",
  "Short loin mollit beef duis eu.  Sirloin short loin id culpa doner do corned beef ipsum excepteur.  Meatball ut alcatra, prosciutto culpa burgdoggen cupidatat capicola bacon buffalo.  Deserunt ut anim cillum exercitation corned beef turkey boudin do beef flank quis tempor spare ribs rump.  Nulla nostrud aliqua voluptate aute dolor cow tenderloin alcatra pig in adipisicing filet mignon fugiat tempor.  Chicken ex labore eiusmod.  Fugiat minim jowl deserunt burgdoggen voluptate exercitation incididunt cupidatat ham hock shankle.",
  "Meatball shank tongue eiusmod ham hock elit tenderloin bresaola prosciutto qui leberkas tri-tip drumstick corned beef.  Buffalo magna frankfurter, id kevin duis short ribs nulla cow in.  Ball tip leberkas dolore biltong.  Elit strip steak ball tip buffalo officia pork loin esse turducken.  Ut prosciutto tenderloin nostrud jerky culpa enim pastrami ribeye.  Labore jerky aliqua meatloaf t-bone.",
  "Ullamco leberkas ut short loin dolore voluptate in.  Nostrud ea esse, nulla dolore pork belly pig tri-tip voluptate in et salami.  Capicola shoulder dolore, frankfurter spare ribs elit turducken occaecat meatloaf nostrud ipsum porchetta et magna ground round.  Cupidatat capicola cupim anim dolore meatloaf rump ribeye irure buffalo.  Nulla enim cow bacon laborum ham ground round andouille corned beef in ipsum.  Minim dolore in tempor incididunt bacon, ball tip nulla buffalo commodo.",
  "Ham biltong id sausage pariatur.  Consequat flank chuck est pork belly excepteur jerky quis pig shankle ham.  Spare ribs capicola occaecat fatback dolore eiusmod strip steak pancetta.  Leberkas meatball pork loin dolore, turkey lorem magna shank bacon kielbasa do.  Esse veniam ex et strip steak ball tip swine do, meatloaf proident ham beef ribs in.",
  "Shoulder nostrud laboris dolor.  Aliquip in mollit ball tip ribeye lorem.  Turducken non brisket hamburger venison.  Shank nulla pastrami rump, short ribs capicola eu tail.  Bresaola anim tri-tip filet mignon, exercitation incididunt cupim ut."
];

const answers = [];
for (let i = 0; i < 50; i++) {
  answers.push({
    answer1: paragraphs[Math.floor(Math.random() * 50)],
    answer2: paragraphs[Math.floor(Math.random() * 50)],
    answer2_choice: Math.floor(Math.random() * 2) === 0 ? "help" : "escape",
    answer3: paragraphs[Math.floor(Math.random() * 50)],
    answer4: paragraphs[Math.floor(Math.random() * 50)],
    answer5: paragraphs[Math.floor(Math.random() * 50)],
    answer6: paragraphs[Math.floor(Math.random() * 50)]
  });
}

exports.seed = function(knex, Promise) {
  return knex("jpc_xv_answers")
    .del()
    .then(function() {
      return knex("jpc_xv_answers").insert(answers);
    });
};
